### ISSUE TITLE
bookmaker_titlepage only runs on every-other conversion

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/covermaker#31]
For any specific title, bookmaker_titlepage seems to only run on every other attempted conversion of that book. Perhaps something is going wrong with the old file deletion or the setting of the gen value? Maybe an order of operations thing (e.g., old titlepage log file gets deleted before the gen variable gets set?).

Temporary fix is to manually delete the images/epubtitlepage.jpg and the logs/titlepage.txt files before each conversion.

**Comment by MacmillanWorkflows** [comment]
@nelliemckesson, I was looking at this b/c the alternating diffs were confusing me re: bookmaker testing -
I think the issue is that the elseif in line 222 is getting invoked every other run because:
• final_cover is getting defined as epubtitlepage in line 196, 
and 
• epubtitlepage is getting defined as the path to an existing epubtitlepage.jpg in line 179, even when no new submitted epubtitlepage exists.  

So in line 222, final_cover exists, gen is set to false and the log and titlepage are deleted.  And then regenerated next run.

The simplest fix that occurs to me would be to change lines 176 & 179 to have epubtitlepage = '' (empty string)..  would something like that work for you?  
(& the same thing for lines 185 & 188)
